//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QMS.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Or Pw incorrect!.
        /// </summary>
        internal static string ACCOUNT_PW {
            get {
                return ResourceManager.GetString("ACCOUNT_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DetaiQcQrCode failed.
        /// </summary>
        internal static string Add_DetaiQcQrCode_failed {
            get {
                return ResourceManager.GetString("Add DetaiQcQrCode failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ProductionProcess failed.
        /// </summary>
        internal static string Add_ProductionProcess_failed {
            get {
                return ResourceManager.GetString("Add ProductionProcess failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Success.
        /// </summary>
        internal static string AddNewSuccess {
            get {
                return ResourceManager.GetString("AddNewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to being repaired.
        /// </summary>
        internal static string beingrepaired {
            get {
                return ResourceManager.GetString("beingrepaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Month.
        /// </summary>
        internal static string BuyMonth {
            get {
                return ResourceManager.GetString("BuyMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Code.
        /// </summary>
        internal static string ByDefectCode {
            get {
                return ResourceManager.GetString("ByDefectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch the error.
        /// </summary>
        internal static string catch_the_error {
            get {
                return ResourceManager.GetString("catch the error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change line.
        /// </summary>
        internal static string change_line {
            get {
                return ResourceManager.GetString("change line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Internet.
        /// </summary>
        internal static string CheckInternet {
            get {
                return ResourceManager.GetString("CheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check QR - Repair.
        /// </summary>
        internal static string CheckQR {
            get {
                return ResourceManager.GetString("CheckQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Factory.
        /// </summary>
        internal static string ChooseFactory {
            get {
                return ResourceManager.GetString("ChooseFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose SewingLine.
        /// </summary>
        internal static string ChooseSewingLine {
            get {
                return ResourceManager.GetString("ChooseSewingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Site.
        /// </summary>
        internal static string ChooseSite {
            get {
                return ResourceManager.GetString("ChooseSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Cleanliness.
        /// </summary>
        internal static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color and size have not been entered.
        /// </summary>
        internal static string color_and_size_have_not_been_entered {
            get {
                return ResourceManager.GetString("color and size have not been entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Repair.
        /// </summary>
        internal static string ConfirmRepair {
            get {
                return ResourceManager.GetString("ConfirmRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Rework.
        /// </summary>
        internal static string ConfirmRework {
            get {
                return ResourceManager.GetString("ConfirmRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Production Report.
        /// </summary>
        internal static string DailyProductionReport {
            get {
                return ResourceManager.GetString("DailyProductionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAILY PRODUCTION REPORT.
        /// </summary>
        internal static string DailyReportTitle {
            get {
                return ResourceManager.GetString("DailyReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range.
        /// </summary>
        internal static string DateRangeInvalid {
            get {
                return ResourceManager.GetString("DateRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        internal static string Defect {
            get {
                return ResourceManager.GetString("Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Search.
        /// </summary>
        internal static string defect_search {
            get {
                return ResourceManager.GetString("defect search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Rate.
        /// </summary>
        internal static string defectpercentage {
            get {
                return ResourceManager.GetString("defectpercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Qty.
        /// </summary>
        internal static string DefectQty {
            get {
                return ResourceManager.GetString("DefectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Success.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Of Product Defects.
        /// </summary>
        internal static string Detailsofproductdefects {
            get {
                return ResourceManager.GetString("Detailsofproductdefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop fix this defect.
        /// </summary>
        internal static string Dontfixthisdefect {
            get {
                return ResourceManager.GetString("Dontfixthisdefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter error code.
        /// </summary>
        internal static string Enter_error_code {
            get {
                return ResourceManager.GetString("Enter error code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Error Information.
        /// </summary>
        internal static string enter_error_information {
            get {
                return ResourceManager.GetString("enter error information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fixed.
        /// </summary>
        internal static string error_fixed {
            get {
                return ResourceManager.GetString("error fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR TRY AGAIN.
        /// </summary>
        internal static string ERROR_TRYAGAIN {
            get {
                return ResourceManager.GetString("ERROR_TRYAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeding The QTY.
        /// </summary>
        internal static string Exceeding_The_Amount {
            get {
                return ResourceManager.GetString("Exceeding_The_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Fabric/3-Accessory.
        /// </summary>
        internal static string FabricAccessory {
            get {
                return ResourceManager.GetString("FabricAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG.
        /// </summary>
        internal static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Good.
        /// </summary>
        internal static string Finishgood {
            get {
                return ResourceManager.GetString("Finishgood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give back.
        /// </summary>
        internal static string give_back {
            get {
                return ResourceManager.GetString("give back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img.
        /// </summary>
        internal static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT INFORMATION.
        /// </summary>
        internal static string INPUTINFORMATION {
            get {
                return ResourceManager.GetString("INPUTINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input QR.
        /// </summary>
        internal static string InputQR {
            get {
                return ResourceManager.GetString("InputQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input QR.
        /// </summary>
        internal static string InputQRcode {
            get {
                return ResourceManager.GetString("InputQRcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside.
        /// </summary>
        internal static string Inside {
            get {
                return ResourceManager.GetString("Inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        internal static string Invalid_Username_or_Password {
            get {
                return ResourceManager.GetString("Invalid Username or Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left+Right.
        /// </summary>
        internal static string LeftRight {
            get {
                return ResourceManager.GetString("LeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN ERROR.
        /// </summary>
        internal static string LOGINERROR {
            get {
                return ResourceManager.GetString("LOGINERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login System.
        /// </summary>
        internal static string Loginsystem {
            get {
                return ResourceManager.GetString("Loginsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-Logo/5-Label.
        /// </summary>
        internal static string Logo_Label {
            get {
                return ResourceManager.GetString("Logo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        internal static string Mid {
            get {
                return ResourceManager.GetString("Mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MidLeft.
        /// </summary>
        internal static string MidLeft {
            get {
                return ResourceManager.GetString("MidLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MidRight.
        /// </summary>
        internal static string MidRight {
            get {
                return ResourceManager.GetString("MidRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Defect On Garment.
        /// </summary>
        internal static string NODEFONGARMENT {
            get {
                return ResourceManager.GetString("NODEFONGARMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Picture.
        /// </summary>
        internal static string NOPICTURE {
            get {
                return ResourceManager.GetString("NOPICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found QRCode.
        /// </summary>
        internal static string NotFoundQRCode {
            get {
                return ResourceManager.GetString("NotFoundQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no workers to fix errors.
        /// </summary>
        internal static string NoWorkersToFix {
            get {
                return ResourceManager.GetString("NoWorkersToFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of remakes:.
        /// </summary>
        internal static string Numberofremakes {
            get {
                return ResourceManager.GetString("Numberofremakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        internal static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        internal static string Outside {
            get {
                return ResourceManager.GetString("Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVER QTY.NOT SAVE.
        /// </summary>
        internal static string OVERQTY_NOTSAVE {
            get {
                return ResourceManager.GetString("OVERQTY_NOTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACKING.
        /// </summary>
        internal static string PACKING {
            get {
                return ResourceManager.GetString("PACKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed product. Do you want to fix it?.
        /// </summary>
        internal static string Passed_product__Do_you_want_to_fix_it_ {
            get {
                return ResourceManager.GetString("Passed product. Do you want to fix it?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Rate.
        /// </summary>
        internal static string passpercentage {
            get {
                return ResourceManager.GetString("passpercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Qty.
        /// </summary>
        internal static string PassQty {
            get {
                return ResourceManager.GetString("PassQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass (RFT).
        /// </summary>
        internal static string PassRFT {
            get {
                return ResourceManager.GetString("PassRFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant camera permission to the device..
        /// </summary>
        internal static string permissiontothedevice {
            get {
                return ResourceManager.GetString("permissiontothedevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        internal static string PO {
            get {
                return ResourceManager.GetString("PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product passed.
        /// </summary>
        internal static string product_passed {
            get {
                return ResourceManager.GetString("product passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qc is checking.
        /// </summary>
        internal static string Qc_is_checking {
            get {
                return ResourceManager.GetString("Qc is checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCheck.
        /// </summary>
        internal static string QcCheckAgain {
            get {
                return ResourceManager.GetString("QcCheckAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Defect.
        /// </summary>
        internal static string QCDefect {
            get {
                return ResourceManager.GetString("QCDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Job.
        /// </summary>
        internal static string QCJob {
            get {
                return ResourceManager.GetString("QCJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Recieving.
        /// </summary>
        internal static string QCRecieving {
            get {
                return ResourceManager.GetString("QCRecieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode.
        /// </summary>
        internal static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR NOT AVAILABLE.
        /// </summary>
        internal static string QRNOTAVAILABLE {
            get {
                return ResourceManager.GetString("QRNOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR is PASSED.
        /// </summary>
        internal static string QRPASSED {
            get {
                return ResourceManager.GetString("QRPASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Scan.
        /// </summary>
        internal static string QtyScan {
            get {
                return ResourceManager.GetString("QtyScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUERY DATA.
        /// </summary>
        internal static string QUERYDATA {
            get {
                return ResourceManager.GetString("QUERYDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Garment.
        /// </summary>
        internal static string RepairGarment {
            get {
                return ResourceManager.GetString("RepairGarment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repalce Fabric.
        /// </summary>
        internal static string Repalce_Fabric {
            get {
                return ResourceManager.GetString("Repalce Fabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return failed.
        /// </summary>
        internal static string Return_failed {
            get {
                return ResourceManager.GetString("Return failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return successful.
        /// </summary>
        internal static string Return_successful {
            get {
                return ResourceManager.GetString("Return successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNED.
        /// </summary>
        internal static string SCANNED {
            get {
                return ResourceManager.GetString("SCANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        internal static string ScanQRcode {
            get {
                return ResourceManager.GetString("ScanQRcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScanQR Login.
        /// </summary>
        internal static string ScanQRLogin {
            get {
                return ResourceManager.GetString("ScanQRLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR QMS.
        /// </summary>
        internal static string ScanQRQMS {
            get {
                return ResourceManager.GetString("ScanQRQMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        internal static string ScanQRQMSQTY {
            get {
                return ResourceManager.GetString("ScanQRQMSQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-Seamseal/Bonding.
        /// </summary>
        internal static string Seamseal_Bonding {
            get {
                return ResourceManager.GetString("Seamseal_Bonding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Item....
        /// </summary>
        internal static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: .
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Factory.
        /// </summary>
        internal static string SelectFactory {
            get {
                return ResourceManager.GetString("SelectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Line.
        /// </summary>
        internal static string SelectLine {
            get {
                return ResourceManager.GetString("SelectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMI.
        /// </summary>
        internal static string SEMI {
            get {
                return ResourceManager.GetString("SEMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMI GOOD.
        /// </summary>
        internal static string Semigood {
            get {
                return ResourceManager.GetString("Semigood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewing Line.
        /// </summary>
        internal static string SewingLine {
            get {
                return ResourceManager.GetString("SewingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sewing Output.
        /// </summary>
        internal static string SewingOutput {
            get {
                return ResourceManager.GetString("SewingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt C. Do you want to Recycle ?.
        /// </summary>
        internal static string Shirt_C__Do_you_want_to_Recycle__ {
            get {
                return ResourceManager.GetString("Shirt C. Do you want to Recycle ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Camera.
        /// </summary>
        internal static string switch_camera {
            get {
                return ResourceManager.GetString("switch camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNABLE TO GET INFOR.
        /// </summary>
        internal static string UNABLETOGETINFOR {
            get {
                return ResourceManager.GetString("UNABLETOGETINFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string UserNameID {
            get {
                return ResourceManager.GetString("UserNameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker is fixing.
        /// </summary>
        internal static string worker_is_fixing {
            get {
                return ResourceManager.GetString("worker is fixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Workmanship/9-SPI.
        /// </summary>
        internal static string Workmanship_SPI {
            get {
                return ResourceManager.GetString("Workmanship_SPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkNo.
        /// </summary>
        internal static string WorkNo {
            get {
                return ResourceManager.GetString("WorkNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes To Confirm.
        /// </summary>
        internal static string YesToConfirm {
            get {
                return ResourceManager.GetString("YesToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string YesToFinish {
            get {
                return ResourceManager.GetString("YesToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string YesToPass {
            get {
                return ResourceManager.GetString("YesToPass", resourceCulture);
            }
        }
    }
}
